spring:
  profiles:
    active: dev
  jpa:
    open-in-view: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/example?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: hong#0618
    tomcat:
      max-active: 4
      min-idle: 2
      initial-size: 2
---
spring:
  profiles: dev

server:
  port: 8080

---
spring:
  profiles: test
